DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_name VARCHAR(255),
  date DATE,
  public BOOLEAN,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
